export const Languages = {
  lotin: {
    home: {
      title: "Bosh sahifa",
      pro: "PRO",
      section_title: "Bo‘limlar",
      departments: {
        exam20: "Imtihon 20 real",
        exam10: "Imtihon 10 real",
        marathon: "Marafon",
        random: "Random",
        saved: "Saqlanganlar",
      },
    },
    tabs: {
      home: "home",
      settings: "Sozlamalar",
      template: "Shablonlar",
      marathon: "Marafon",
      offer: "Taklif",
    },
    settings: {
      title: "Sozlamalar",
      sections: {
        extras: "Qo’shimchalar",
        others: "Boshqalar",
        contact: "Aloqalar",
      },
      options: {
        extract_colors: "Ranglarni ajratib olish",
        fines: "Jarimalar",
        road_signs: "Yo‘l belgilar",
        video_guide: "Video qo‘llanma",
        all_questions: "Barcha savollar",
        dark_mode: "Tungi rejim",
        app_language: "Ilova tili",
        keep_screen_on: "Ekran doim yoniq",
        vibration: "Vibratsiya",
        telegram: "Telegram",
        instagram: "Instagram",
        privacy_policy: "Privacy policy",
        rate_app: "Ilovani baholash",
        share_app: "Do‘stlarga ulashish",
        about_app: "Dastur haqida",
        choose_language: "Tilni tanlang",
        uzbek: "Uzbek",
        russian: "Rus",
        cyrillic: "Kiril",
        version: "Versiya",
      },
    },
    offer: {
      title: "Takliflar",
      tab1: "Taklif qilish",
      tab2: "Qo‘shilish",
      tab1_description:
        "Do’stlaringizni taklif qiling va sovg’alarga ega bo’ling",
      tab2_description: "Havola raqamini kiriting va sovg’alarga ega bo’ling",
      input_placeholder: "Id kiriting",
      send: "Yuborish",
      invited_users: "Taklif qilinganlar",
      not_found: "Ma’lumot topilmadi",
    },
    template: {
      title: "Biletlar",
      my_result: "Mening natijam",
      true_answers: "To’g’ri javob",
      false_answers: "Notog'ri javob",
      marathon: "Marafon",
      tickets: {
        ten_ticket: "10 talik biletlar",
        twenty_ticket: "20 talik biletlar",
        three_hundred_ticket: "300 talik biletlar",
        five_hundred_ticket: "500 talik biletlar",
      },
      tickets_title: "Biletlar",
      ticket: {
        title: "Bilet",
        my_result: "Mening natijam",
        true_answers: "To’g’ri javob",
        false_answers: "Notog'ri javob",
      },
      result_title: "Natija",
      used: "To‘g‘ri",
      rejected: "Noto‘g‘ri",
    },
    marathon: {
      title: "Biletlar",
      my_result: "Mening natijam",
      true_answers: "To’g’ri javob",
      false_answers: "Notog'ri javob",
      start: "Boshlash",
      description: `Imtihon 20 ta savoldan iborat bo’lib kamida18 tasavolga javob berilganida testdan o’tilgan hisoblanadi. Imtihon 25 daqiqa davom etadi. Test topshirilganidan so’ng natijalaringizni bilib olishingiz mumkin `,
      marathon_title: "Marafon",
    },
    modals: {
      pro_purchase_title: "Pro versiyani sotib olmoqchimisiz ?",
      too_many_errors_title: "Siz juda ko‘p xato qildingiz!",
      try_again_question: "Qaytadan sinab ko‘rishni xohlaysizmi ?",
      yes: "HA",
      no: "YO‘Q",
      finish_ticket_warning: "Biletni tugatsangiz natijalar saqlanib qolmaydi",
      finish_ticket_question: "Biletni tugatasizmi ?",
    },
  },
  rus: {
    home: {
      title: "Главная страница",
      pro: "ПРО",
      section_title: "Разделы",
      departments: {
        exam20: "Экзамен 20 вопросов",
        exam10: "Экзамен 10 вопросов",
        marathon: "Марафон",
        random: "Случайный",
        saved: "Сохранённые",
      },
    },
    tabs: {
      home: "Главная",
      settings: "Настройки",
      template: "Шаблоны",
      marathon: "Марафон",
      offer: "Предложение",
    },
    settings: {
      title: "Настройки",
      sections: {
        extras: "Дополнительно",
        others: "Другое",
        contact: "Контакты",
      },
      options: {
        extract_colors: "Извлечение цветов",
        fines: "Штрафы",
        road_signs: "Дорожные знаки",
        video_guide: "Видео руководство",
        all_questions: "Все вопросы",
        dark_mode: "Темная тема",
        app_language: "Язык приложения",
        keep_screen_on: "Экран всегда включен",
        vibration: "Вибрация",
        telegram: "Телеграм",
        instagram: "Инстаграм",
        privacy_policy: "Политика конфиденциальности",
        rate_app: "Оценить приложение",
        share_app: "Поделиться с друзьями",
        about_app: "О приложении",
        choose_language: "Выберите язык",
        uzbek: "Узбекский",
        russian: "Русский",
        cyrillic: "Кириллический",
        version: "Версия",
      },
    },
    offer: {
      title: "Приглашения",
      tab1: "Пригласить",
      tab2: "Присоединиться",
      tab1_description: "Пригласите своих друзей и получите подарки",
      tab2_description: "Введите реферальный код и получите подарки",
      input_placeholder: "Введите ID",
      send: "Отправить",
      invited_users: "Приглашённые пользователи",
      not_found: "Информация не найдена",
    },
    template: {
      title: "Билеты",
      my_result: "Мой результат",
      true_answers: "Правильный ответ",
      false_answers: "Неправильный ответ",
      marathon: "Марафон",
      tickets: {
        ten_ticket: "10 билетные",
        twenty_ticket: "20 билетные",
        three_hundred_ticket: "300 билетные",
        five_hundred_ticket: "500 билетные",
      },
      tickets_title: "Билеты",
      ticket: {
        title: "Билет",
        my_result: "Мой результат",
        true_answers: "Правильный ответ",
        false_answers: "Неправильный ответ",
      },
      result_title: "Результат",
      used: "Количество правильных",
      rejected: "Количество неправильных",
    },
    marathon: {
      title: "Билеты",
      my_result: "Мой результат",
      true_answers: "Правильный ответ",
      false_answers: "Неправильный ответ",
      start: "Начать",
      description: `Экзамен состоит из 20 вопросов. Чтобы пройти тест, необходимо правильно ответить как минимум на 18. Экзамен длится 25 минут. После сдачи теста вы сможете увидеть свои результаты.`,
      marathon_title: "Марафон",
    },
    modals: {
      pro_purchase_title: "Хотите купить Pro версию?",
      too_many_errors_title: "Вы допустили слишком много ошибок!",
      try_again_question: "Хотите попробовать снова?",
      yes: "ДА",
      no: "НЕТ",
      finish_ticket_warning:
        "Если вы завершите билет, результаты не сохранятся",
      finish_ticket_question: "Завершить билет?",
    },
  },
  krill: {
    home: {
      title: "Бош саҳифа",
      pro: "PRO",
      section_title: "Бўлимлар",
      departments: {
        exam20: "Имтиҳон 20 реал",
        exam10: "Имтиҳон 10 реал",
        marathon: "Марафон",
        random: "Тасодифий",
        saved: "Сақланганлар",
      },
    },
    tabs: {
      home: "Бош саҳифа",
      settings: "Созламалар",
      template: "Шаблонлар",
      marathon: "Марафон",
      offer: "Таклиф",
    },
    settings: {
      title: "Созламалар",
      sections: {
        extras: "Қўшимчалар",
        others: "Бошқалар",
        contact: "Алоқалар",
      },
      options: {
        extract_colors: "Рангларни ажратиб олиш",
        fines: "Жарималар",
        road_signs: "Йўл белгилари",
        video_guide: "Видео қўлланма",
        all_questions: "Барча саволлар",
        dark_mode: "Тунги режим",
        app_language: "Илова тили",
        keep_screen_on: "Экран доим ёниқ",
        vibration: "Вибрация",
        telegram: "Телеграм",
        instagram: "Инстаграм",
        privacy_policy: "Махфийлик сиёсати",
        rate_app: "Иловани баҳолаш",
        share_app: "Дўстларга улашиш",
        about_app: "Дастур ҳақида",
        choose_language: "Тилни танланг",
        uzbek: "Ўзбекча",
        russian: "Русча",
        cyrillic: "Кирил",
        version: "Версия",
      },
    },
    offer: {
      title: "Таклифлар",
      tab1: "Таклиф қилиш",
      tab2: "Қўшилиш",
      tab1_description:
        "Дўстларингизни таклиф қилинг ва совғалаларга эга бўлинг",
      tab2_description: "Ҳавола рақамини киритинг ва совғалаларга эга бўлинг",
      input_placeholder: "ID киритинг",
      send: "Юбориш",
      invited_users: "Таклиф қилинганлар",
      not_found: "Маълумот топилмади",
    },
    template: {
      title: "Билетлар",
      my_result: "Менинг натижам",
      true_answers: "Тўғри жавоб",
      false_answers: "Нотўғри жавоб",
      marathon: "Марафон",
      tickets: {
        ten_ticket: "10 талик билетлар",
        twenty_ticket: "20 талик билетлар",
        three_hundred_ticket: "300 талик билетлар",
        five_hundred_ticket: "500 талик билетлар",
      },
      tickets_title: "Билетлар",
      ticket: {
        title: "Билет",
        my_result: "Менинг натижам",
        true_answers: "Тўғри жавоб",
        false_answers: "Нотўғри жавоб",
      },
      result_title: "Натижа",
      used: "Тўғри сони",
      rejected: "Нотўғри сони",
    },
    marathon: {
      title: "Билетлар",
      my_result: "Менинг натижам",
      true_answers: "Тўғри жавоб",
      false_answers: "Нотўғри жавоб",
      start: "Бошлаш",
      description: `Имтиҳон 20 та саволдан иборат бўлиб, камида 18 та саволга жавоб берилганда тестдан ўтган ҳисобланади. Имтиҳон 25 дақиқа давом этади. Тест топширилгандан сўнг натижаларингизни билиб олишингиз мумкин.`,
      marathon_title: "Марафон",
    },
    modals: {
      pro_purchase_title: "Про версияни сотиб олмоқчимисиз?",
      too_many_errors_title: "Сиз жуда кўп хато қилдингиз!",
      try_again_question: "Қайтадан синаб кўришни хоҳлайсизми?",
      yes: "ҲА",
      no: "ЙЎҚ",
      finish_ticket_warning: "Билетни тугатсангиз натижалар сақланмайди",
      finish_ticket_question: "Билетни тугатасизми?",
    },
  },
};
