export const SIGN_CATEGORIES = [
  {
    key: "ogohlantiruvchi",
    icon: "warning",
    order: 1,
    name: { lotin: "Ogohlantiruvchi belgilar", krill: "Огоҳлантирувчи белгилар", rus: "Предупреждающие знаки" }
  },
  {
    key: "imtiyoz",
    icon: "priority",
    order: 2,
    name: { lotin: "Imtiyoz belgilari", krill: "Имтиёз белгилари", rus: "Знаки приоритета" }
  },
  {
    key: "taqiqlovchi",
    icon: "no-entry",
    order: 3,
    name: { lotin: "Taqiqlovchi belgilar", krill: "Тақиқловчи белгилар", rus: "Запрещающие знаки" }
  },
  {
    key: "buyuruvchi",
    icon: "arrow",
    order: 4,
    name: { lotin: "Buyuruvchi belgilar", krill: "Буюрувчи белгилар", rus: "Предписывающие знаки" }
  },
  {
    key: "axborot-ishora",
    icon: "info",
    order: 5,
    name: { lotin: "Axborot-ishora belgilari", krill: "Ахборот-ишора белгилари", rus: "Информационно-указательные знаки" }
  },
  {
    key: "servis",
    icon: "service",
    order: 6,
    name: { lotin: "Servis belgilari", krill: "Сервис белгилари", rus: "Знаки сервиса" }
  },
  {
    key: "qoshimcha-axborot",
    icon: "plate",
    order: 7,
    name: { lotin: "Qo'shimcha axborot belgilari", krill: "Қўшимча ахборот белгилари", rus: "Знаки дополнительной информации" }
  },
  {
    key: "transport-taniqlik",
    icon: "badge",
    order: 8,
    name: {
      lotin: "Transport vositalarining taniqlik belgilari",
      krill: "Транспорт воситаларининг таниқлик белгилари",
      rus: "Опознавательные знаки транспортных средств"
    }
  }
];

export const ROAD_SIGNS = [
  // --- Ogohlantiruvchi (warning) ---
  { number: "1.1", category: "ogohlantiruvchi", shape: "triangle", svgKey: "railway",
    nameLotin: "Shlagbaumli temir yo'l kesishmasi", nameRus: "Железнодорожный переезд со шлагбаумом",
    descLotin: "Oldinda shlagbaum bilan jihozlangan temir yo'l kesishmasi borligini bildiradi.",
    descRus: "Впереди железнодорожный переезд, оборудованный шлагбаумом." },
  { number: "1.2", category: "ogohlantiruvchi", shape: "triangle", svgKey: "railway-open",
    nameLotin: "Shlagbaumsiz temir yo'l kesishmasi", nameRus: "Железнодорожный переезд без шлагбаума",
    descLotin: "Oldinda shlagbaumsiz temir yo'l kesishmasi borligini bildiradi, ehtiyot bo'lish zarur.",
    descRus: "Впереди железнодорожный переезд без шлагбаума." },
  { number: "1.3.1", category: "ogohlantiruvchi", shape: "triangle",
    nameLotin: "Bir yo'lli temir yo'l", nameRus: "Однопутная железная дорога",
    descLotin: "Kesishmadagi temir yo'l bitta yo'ldan iboratligini bildiradi.",
    descRus: "Железная дорога на переезде имеет один путь." },
  { number: "1.3.2", category: "ogohlantiruvchi", shape: "triangle",
    nameLotin: "Ko'p yo'lli temir yo'l", nameRus: "Многопутная железная дорога",
    descLotin: "Kesishmadagi temir yo'l ikki va undan ortiq yo'ldan iboratligini bildiradi.",
    descRus: "Железная дорога на переезде имеет два и более пути." },
  { number: "1.5", category: "ogohlantiruvchi", shape: "triangle",
    nameLotin: "Temir yo'l bilan kesishish yo'nalishi", nameRus: "Пересечение с железной дорогой",
    descLotin: "Yo'lning temir yo'l bilan kesishish burchagini bildiradi.",
    descRus: "Показывает направление пересечения дороги с железнодорожными путями." },
  { number: "1.6", category: "ogohlantiruvchi", shape: "triangle", svgKey: "crossroad",
    nameLotin: "Teng ahamiyatli yo'llar kesishmasi", nameRus: "Пересечение равнозначных дорог",
    descLotin: "Oldinda barcha yo'nalishlari teng huquqli kesishma borligini bildiradi.",
    descRus: "Впереди перекрёсток равнозначных дорог." },
  { number: "1.7", category: "ogohlantiruvchi", shape: "triangle", svgKey: "roundabout",
    nameLotin: "Aylanma harakat bilan kesishma", nameRus: "Пересечение с круговым движением",
    descLotin: "Oldinda aylanma harakat tashkil etilgan kesishma borligini bildiradi.",
    descRus: "Впереди перекрёсток с круговым движением." },
  { number: "1.8", category: "ogohlantiruvchi", shape: "triangle", svgKey: "traffic-light",
    nameLotin: "Svetofor bilan tartibga solinadigan kesishma", nameRus: "Светофорное регулирование",
    descLotin: "Oldinda svetofor bilan boshqariladigan uchastka borligini bildiradi.",
    descRus: "Впереди участок дороги, движение на котором регулируется светофором." },
  { number: "1.9", category: "ogohlantiruvchi", shape: "triangle",
    nameLotin: "Ko'tariladigan ko'prik", nameRus: "Разводной мост",
    descLotin: "Oldinda ko'tariladigan yoki keminigacha ko'prik borligini bildiradi.",
    descRus: "Впереди разводной мост или паромная переправа." },
  { number: "1.11.1", category: "ogohlantiruvchi", shape: "triangle", svgKey: "curve-left",
    nameLotin: "Xavfli burilish (chapga)", nameRus: "Опасный поворот налево",
    descLotin: "Yo'lning kam ko'rinuvchan chapga xavfli burilishini bildiradi.",
    descRus: "Дорога с опасным поворотом налево." },
  { number: "1.11.2", category: "ogohlantiruvchi", shape: "triangle", svgKey: "curve-right",
    nameLotin: "Xavfli burilish (o'ngga)", nameRus: "Опасный поворот направо",
    descLotin: "Yo'lning kam ko'rinuvchan o'ngga xavfli burilishini bildiradi.",
    descRus: "Дорога с опасным поворотом направо." },
  { number: "1.13", category: "ogohlantiruvchi", shape: "triangle", svgKey: "descent",
    nameLotin: "Tik tushish", nameRus: "Крутой спуск",
    descLotin: "Yo'lning tik pastga tushishini bildiradi.",
    descRus: "Крутой спуск на дороге." },
  { number: "1.14", category: "ogohlantiruvchi", shape: "triangle", svgKey: "ascent",
    nameLotin: "Tik ko'tarilish", nameRus: "Крутой подъём",
    descLotin: "Yo'lning tik yuqoriga ko'tarilishini bildiradi.",
    descRus: "Крутой подъём на дороге." },
  { number: "1.15", category: "ogohlantiruvchi", shape: "triangle", svgKey: "slippery",
    nameLotin: "Sirg'anchiq yo'l", nameRus: "Скользкая дорога",
    descLotin: "Qatnov qismi sirg'anchiq bo'lishi mumkinligini bildiradi.",
    descRus: "Участок дороги с повышенной скользкостью проезжей части." },
  { number: "1.16", category: "ogohlantiruvchi", shape: "triangle",
    nameLotin: "Notekis yo'l", nameRus: "Неровная дорога",
    descLotin: "Qatnov qismida notekisliklar (chuqurcha, do'mboq) borligini bildiradi.",
    descRus: "Участок дороги с неровностями проезжей части." },
  { number: "1.17", category: "ogohlantiruvchi", shape: "triangle", svgKey: "bump",
    nameLotin: "Sun'iy g'adir-budurlik", nameRus: "Искусственная неровность",
    descLotin: "Qatnov qismida tezlikni cheklovchi sun'iy do'mboq borligini bildiradi.",
    descRus: "Участок дороги с искусственной неровностью." },
  { number: "1.19", category: "ogohlantiruvchi", shape: "triangle", svgKey: "narrow",
    nameLotin: "Qatnov qismining torayishi", nameRus: "Сужение дороги",
    descLotin: "Qatnov qismi kengligi ikkala tomondan torayishini bildiradi.",
    descRus: "Сужение проезжей части с обеих сторон." },
  { number: "1.21", category: "ogohlantiruvchi", shape: "triangle",
    nameLotin: "Qarama-qarshi harakat", nameRus: "Двустороннее движение",
    descLotin: "Bir tomonlama yo'ldan keyin ikki tomonlama harakat boshlanishini bildiradi.",
    descRus: "Начало участка дороги со встречным движением." },
  { number: "1.22", category: "ogohlantiruvchi", shape: "triangle", svgKey: "pedestrian-crossing",
    nameLotin: "Piyodalar o'tish joyi", nameRus: "Пешеходный переход",
    descLotin: "Oldinda piyodalar o'tish joyi borligini bildiradi.",
    descRus: "Впереди обозначенный пешеходный переход." },
  { number: "1.23", category: "ogohlantiruvchi", shape: "triangle", svgKey: "children",
    nameLotin: "Bolalar", nameRus: "Дети",
    descLotin: "Yaqin atrofda bolalar chiqishi mumkin bo'lgan joy (maktab, bog'cha) borligini bildiradi.",
    descRus: "Участок дороги вблизи детского учреждения, где возможно появление детей." },
  { number: "1.24", category: "ogohlantiruvchi", shape: "triangle", svgKey: "bicycle",
    nameLotin: "Velosipedchilar bilan kesishish", nameRus: "Пересечение с велосипедной дорожкой",
    descLotin: "Velosiped yo'lining avtomobil yo'li bilan kesishishini bildiradi.",
    descRus: "Пересечение дороги с велосипедной дорожкой." },
  { number: "1.25", category: "ogohlantiruvchi", shape: "triangle", svgKey: "roadworks",
    nameLotin: "Yo'l ta'mirlash ishlari", nameRus: "Дорожные работы",
    descLotin: "Oldinda yo'l ta'mirlash ishlari olib borilayotganini bildiradi.",
    descRus: "Впереди участок дороги, на котором проводятся ремонтные работы." },
  { number: "1.26", category: "ogohlantiruvchi", shape: "triangle",
    nameLotin: "Chorva mollari haydash", nameRus: "Перегон скота",
    descLotin: "Yo'l orqali chorva mollari haydalishi mumkinligini bildiradi.",
    descRus: "Участок дороги, на котором возможен перегон скота." },
  { number: "1.27", category: "ogohlantiruvchi", shape: "triangle",
    nameLotin: "Yovvoyi hayvonlar", nameRus: "Дикие животные",
    descLotin: "Yo'lga yovvoyi hayvonlar chiqishi mumkinligini bildiradi.",
    descRus: "Участок дороги, на котором возможен выход диких животных." },
  { number: "1.31", category: "ogohlantiruvchi", shape: "triangle", svgKey: "tunnel",
    nameLotin: "Tunnel", nameRus: "Тоннель",
    descLotin: "Oldinda yoritilmagan yoki yetarli yoritilmagan tunnel borligini bildiradi.",
    descRus: "Впереди тоннель." },
  { number: "1.32", category: "ogohlantiruvchi", shape: "triangle",
    nameLotin: "Tirbandlik", nameRus: "Затор",
    descLotin: "Oldinda transport vositalari tirbandligi ehtimoli borligini bildiradi.",
    descRus: "Участок дороги, на котором возможен затор." },
  { number: "1.33", category: "ogohlantiruvchi", shape: "triangle", svgKey: "danger",
    nameLotin: "Boshqa xavflar", nameRus: "Прочие опасности",
    descLotin: "Boshqa belgilar bilan ko'rsatilmagan xavfli uchastka borligini bildiradi.",
    descRus: "Участок дороги с опасностью, не предусмотренной другими знаками." },

  // --- Imtiyoz (priority) — all 9 official signs ---
  { number: "2.1", category: "imtiyoz", shape: "diamond", svgKey: "main-road",
    nameLotin: "Bosh yo'l", nameRus: "Главная дорога",
    descLotin: "Kesishmadan bosh yo'l bo'ylab ustunlik bilan o'tish huquqini beradi.",
    descRus: "Дорога, на которой предоставляется преимущественное право проезда нерегулируемых перекрёстков." },
  { number: "2.2", category: "imtiyoz", shape: "diamond", svgKey: "main-road-end",
    nameLotin: "Bosh yo'lning tugashi", nameRus: "Конец главной дороги",
    descLotin: "Bosh yo'l maqomining tugaganini bildiradi.",
    descRus: "Обозначает конец главной дороги." },
  { number: "2.3.1", category: "imtiyoz", shape: "triangle", svgKey: "side-road",
    nameLotin: "Ikkinchi darajali yo'l bilan kesishma", nameRus: "Пересечение с второстепенной дорогой",
    descLotin: "Oldinda ikkinchi darajali yo'l qo'shiladigan kesishma borligini bildiradi.",
    descRus: "Пересечение с второстепенной дорогой." },
  { number: "2.4", category: "imtiyoz", shape: "invert-triangle", svgKey: "give-way",
    nameLotin: "Yo'l bering", nameRus: "Уступите дорогу",
    descLotin: "Haydovchi kesishayotgan yo'ldagi transport vositalariga yo'l berishi shartligini bildiradi.",
    descRus: "Водитель обязан уступить дорогу транспортным средствам на пересекаемой дороге." },
  { number: "2.5", category: "imtiyoz", shape: "octagon", svgKey: "stop",
    nameLotin: "To'xtamasdan harakatlanish taqiqlanadi", nameRus: "Движение без остановки запрещено",
    descLotin: "Haydovchi \"Yo'l bering\" chizig'i oldida albatta to'xtashi shart.",
    descRus: "Запрещается движение без остановки перед стоп-линией." },
  { number: "2.6", category: "imtiyoz", shape: "square-blue",
    nameLotin: "O'zaro harakatlanish ustunligi", nameRus: "Преимущество встречного движения",
    descLotin: "Tor uchastkada qarama-qarshi tomondan keluvchi transportga ustunlik berilishini bildiradi.",
    descRus: "Преимущество имеют транспортные средства встречного направления на узком участке." },
  { number: "2.7", category: "imtiyoz", shape: "square-blue",
    nameLotin: "Qarama-qarshi harakatga nisbatan ustunlik", nameRus: "Преимущество перед встречным движением",
    descLotin: "Tor uchastkadan o'tishda haydovchiga ustunlik berilganini bildiradi.",
    descRus: "Водитель имеет преимущество перед встречным транспортом на узком участке." },

  // --- Taqiqlovchi (prohibitory) ---
  { number: "3.1", category: "taqiqlovchi", shape: "circle-red", svgKey: "no-entry",
    nameLotin: "Harakatlanish taqiqlangan", nameRus: "Движение запрещено",
    descLotin: "Barcha transport vositalarining harakatlanishi taqiqlanganini bildiradi.",
    descRus: "Движение всех транспортных средств запрещено." },
  { number: "3.2", category: "taqiqlovchi", shape: "circle-red",
    nameLotin: "Mexanik transportda harakatlanish taqiqlangan", nameRus: "Движение механических ТС запрещено",
    descLotin: "Barcha mexanik transport vositalarining harakatlanishi taqiqlanganini bildiradi.",
    descRus: "Движение всех механических транспортных средств запрещено." },
  { number: "3.3", category: "taqiqlovchi", shape: "circle-red", svgKey: "truck-ban",
    nameLotin: "Yuk avtomobillarida harakatlanish taqiqlangan", nameRus: "Движение грузовых автомобилей запрещено",
    descLotin: "Belgida ko'rsatilgan yuk ko'tarish qobiliyatidan ortiq yuk avtomobillariga taqiqlanadi.",
    descRus: "Запрещено движение грузовых автомобилей с разрешённой максимальной массой более указанной." },
  { number: "3.4", category: "taqiqlovchi", shape: "circle-red",
    nameLotin: "Tirkamali harakatlanish taqiqlangan", nameRus: "Движение с прицепом запрещено",
    descLotin: "Tirkama bilan harakatlanish taqiqlanganini bildiradi.",
    descRus: "Запрещено движение с прицепом." },
  { number: "3.5", category: "taqiqlovchi", shape: "circle-red", svgKey: "motorcycle-ban",
    nameLotin: "Mototsiklda harakatlanish taqiqlangan", nameRus: "Движение на мотоциклах запрещено",
    descLotin: "Mototsikllarning harakatlanishi taqiqlanganini bildiradi.",
    descRus: "Движение мотоциклов запрещено." },
  { number: "3.11", category: "taqiqlovchi", shape: "circle-red", svgKey: "weight-limit",
    nameLotin: "Massasi cheklangan", nameRus: "Ограничение массы",
    descLotin: "Umumiy massasi belgida ko'rsatilgandan ortiq transport vositalariga taqiqlanadi.",
    descRus: "Запрещено движение ТС с общей массой более указанной." },
  { number: "3.13", category: "taqiqlovchi", shape: "circle-red", svgKey: "height-limit",
    nameLotin: "Balandligi cheklangan", nameRus: "Ограничение высоты",
    descLotin: "Balandligi belgida ko'rsatilgandan ortiq transport vositalariga taqiqlanadi.",
    descRus: "Запрещено движение ТС высотой более указанной." },
  { number: "3.14", category: "taqiqlovchi", shape: "circle-red",
    nameLotin: "Kengligi cheklangan", nameRus: "Ограничение ширины",
    descLotin: "Kengligi belgida ko'rsatilgandan ortiq transport vositalariga taqiqlanadi.",
    descRus: "Запрещено движение ТС шириной более указанной." },
  { number: "3.16", category: "taqiqlovchi", shape: "circle-red",
    nameLotin: "Oraliq masofa cheklangan", nameRus: "Ограничение минимальной дистанции",
    descLotin: "Ko'rsatilgandan kam masofada harakatlanish taqiqlanadi.",
    descRus: "Запрещено движение с дистанцией менее указанной." },
  { number: "3.18.1", category: "taqiqlovchi", shape: "circle-red", svgKey: "no-right",
    nameLotin: "O'ngga burilish taqiqlangan", nameRus: "Поворот направо запрещён",
    descLotin: "O'ngga burilish taqiqlanganini bildiradi.",
    descRus: "Запрещён поворот направо." },
  { number: "3.18.2", category: "taqiqlovchi", shape: "circle-red", svgKey: "no-left",
    nameLotin: "Chapga burilish taqiqlangan", nameRus: "Поворот налево запрещён",
    descLotin: "Chapga burilish taqiqlanganini bildiradi.",
    descRus: "Запрещён поворот налево." },
  { number: "3.19", category: "taqiqlovchi", shape: "circle-red", svgKey: "no-u-turn",
    nameLotin: "Aylanib o'tish taqiqlangan", nameRus: "Разворот запрещён",
    descLotin: "Aylanib (U-burilish) o'tish taqiqlanganini bildiradi.",
    descRus: "Разворот запрещён." },
  { number: "3.20", category: "taqiqlovchi", shape: "circle-red", svgKey: "no-overtake",
    nameLotin: "Ozib o'tish taqiqlangan", nameRus: "Обгон запрещён",
    descLotin: "Barcha transport vositalarini ozib o'tish taqiqlanganini bildiradi.",
    descRus: "Обгон всех транспортных средств запрещён." },
  { number: "3.24", category: "taqiqlovchi", shape: "circle-red", svgKey: "speed-limit",
    nameLotin: "Eng katta tezlik cheklangan", nameRus: "Ограничение максимальной скорости",
    descLotin: "Belgida ko'rsatilgandan yuqori tezlikda harakatlanish taqiqlanadi.",
    descRus: "Запрещено движение со скоростью более указанной." },
  { number: "3.27", category: "taqiqlovchi", shape: "circle-red", svgKey: "no-stopping",
    nameLotin: "To'xtash taqiqlangan", nameRus: "Остановка запрещена",
    descLotin: "Transport vositalarining to'xtashi va turishi taqiqlanganini bildiradi.",
    descRus: "Остановка и стоянка транспортных средств запрещена." },
  { number: "3.28", category: "taqiqlovchi", shape: "circle-red", svgKey: "no-parking",
    nameLotin: "To'xtab turish taqiqlangan", nameRus: "Стоянка запрещена",
    descLotin: "Transport vositalarining to'xtab turishi taqiqlanganini bildiradi.",
    descRus: "Стоянка транспортных средств запрещена." },
  { number: "3.31", category: "taqiqlovchi", shape: "circle-white",
    nameLotin: "Barcha taqiqlashlarning tugashi", nameRus: "Конец всех ограничений",
    descLotin: "Bir nechta taqiqlovchi belgilar amali bir vaqtda tugaganini bildiradi.",
    descRus: "Обозначает конец зоны действия сразу нескольких запрещающих знаков." },

  // --- Buyuruvchi (mandatory) ---
  { number: "4.1.1", category: "buyuruvchi", shape: "circle-blue", svgKey: "straight",
    nameLotin: "To'g'riga harakatlanish", nameRus: "Движение прямо",
    descLotin: "Faqat to'g'riga harakatlanishga ruxsat berilganini bildiradi.",
    descRus: "Разрешено движение только прямо." },
  { number: "4.1.2", category: "buyuruvchi", shape: "circle-blue", svgKey: "right",
    nameLotin: "O'ngga harakatlanish", nameRus: "Движение направо",
    descLotin: "Faqat o'ngga harakatlanishga ruxsat berilganini bildiradi.",
    descRus: "Разрешено движение только направо." },
  { number: "4.1.3", category: "buyuruvchi", shape: "circle-blue", svgKey: "left",
    nameLotin: "Chapga harakatlanish", nameRus: "Движение налево",
    descLotin: "Faqat chapga harakatlanishga ruxsat berilganini bildiradi.",
    descRus: "Разрешено движение только налево." },
  { number: "4.1.4", category: "buyuruvchi", shape: "circle-blue",
    nameLotin: "To'g'riga yoki o'ngga", nameRus: "Прямо или направо",
    descLotin: "To'g'riga yoki o'ngga harakatlanishga ruxsat berilganini bildiradi.",
    descRus: "Разрешено движение прямо или направо." },
  { number: "4.1.5", category: "buyuruvchi", shape: "circle-blue",
    nameLotin: "To'g'riga yoki chapga", nameRus: "Прямо или налево",
    descLotin: "To'g'riga yoki chapga harakatlanishga ruxsat berilganini bildiradi.",
    descRus: "Разрешено движение прямо или налево." },
  { number: "4.2.1", category: "buyuruvchi", shape: "circle-blue", svgKey: "pass-right",
    nameLotin: "To'siqni o'ngdan aylanib o'tish", nameRus: "Объезд препятствия справа",
    descLotin: "To'siqni faqat o'ng tomondan aylanib o'tish kerakligini bildiradi.",
    descRus: "Объезжать препятствие разрешается только справа." },
  { number: "4.2.2", category: "buyuruvchi", shape: "circle-blue", svgKey: "pass-left",
    nameLotin: "To'siqni chapdan aylanib o'tish", nameRus: "Объезд препятствия слева",
    descLotin: "To'siqni faqat chap tomondan aylanib o'tish kerakligini bildiradi.",
    descRus: "Объезжать препятствие разрешается только слева." },
  { number: "4.3", category: "buyuruvchi", shape: "circle-blue", svgKey: "roundabout-mandatory",
    nameLotin: "Aylanma harakat", nameRus: "Круговое движение",
    descLotin: "Kesishmadan faqat ko'rsatilgan yo'nalishda (aylana bo'ylab) o'tish kerakligini bildiradi.",
    descRus: "Движение по перекрёстку разрешено только в указанном круговом направлении." },
  { number: "4.4.1", category: "buyuruvchi", shape: "circle-blue", svgKey: "bicycle-lane",
    nameLotin: "Velosiped yo'li", nameRus: "Велосипедная дорожка",
    descLotin: "Yo'lakning faqat velosipedchilar uchun mo'ljallanganini bildiradi.",
    descRus: "Путь предназначен только для велосипедистов." },
  { number: "4.5.1", category: "buyuruvchi", shape: "circle-blue", svgKey: "footpath",
    nameLotin: "Piyodalar yo'li", nameRus: "Пешеходная дорожка",
    descLotin: "Yo'lakning faqat piyodalar uchun mo'ljallanganini bildiradi.",
    descRus: "Путь предназначен только для пешеходов." },
  { number: "4.6", category: "buyuruvchi", shape: "circle-blue",
    nameLotin: "Eng kam tezlik chegarasi", nameRus: "Ограничение минимальной скорости",
    descLotin: "Belgida ko'rsatilgandan kam tezlikda harakatlanish taqiqlanadi.",
    descRus: "Запрещено движение со скоростью менее указанной." },

  // --- Axborot-ishora (informational) ---
  { number: "5.1", category: "axborot-ishora", shape: "square-blue", svgKey: "highway",
    nameLotin: "Avtomagistral", nameRus: "Автомагистраль",
    descLotin: "Yo'l avtomagistral talablariga javob berishini bildiradi.",
    descRus: "Дорога соответствует требованиям, предъявляемым к автомагистралям." },
  { number: "5.2", category: "axborot-ishora", shape: "square-blue",
    nameLotin: "Avtomagistralning tugashi", nameRus: "Конец автомагистрали",
    descLotin: "Avtomagistral uchastkasi tugaganini bildiradi.",
    descRus: "Обозначает конец автомагистрали." },
  { number: "5.5", category: "axborot-ishora", shape: "square-blue", svgKey: "one-way",
    nameLotin: "Bir tomonlama harakat yo'li", nameRus: "Дорога с односторонним движением",
    descLotin: "Qatnov qismi bo'ylab transport faqat bir yo'nalishda harakatlanishini bildiradi.",
    descRus: "Дорога, по всей ширине которой движение осуществляется в одном направлении." },
  { number: "5.8", category: "axborot-ishora", shape: "square-blue",
    nameLotin: "Qarama-qarshi harakat", nameRus: "Реверсивное движение",
    descLotin: "Reversiv svetofor bilan boshqariladigan yo'l boshlanganini bildiradi.",
    descRus: "Начало участка дороги с реверсивным движением." },
  { number: "5.10", category: "axborot-ishora", shape: "square-blue", svgKey: "bus-stop",
    nameLotin: "Avtobus to'xtash joyi", nameRus: "Место остановки автобуса",
    descLotin: "Avtobus (marshrut taksi) to'xtash bekati joylashganini bildiradi.",
    descRus: "Обозначает место остановки автобуса и (или) маршрутного такси." },
  { number: "5.14", category: "axborot-ishora", shape: "square-blue", svgKey: "pedestrian-crossing",
    nameLotin: "Piyodalar o'tish joyi", nameRus: "Пешеходный переход",
    descLotin: "Qatnov qismidagi piyodalar o'tish joyi chegarasini bildiradi.",
    descRus: "Обозначает границы пешеходного перехода." },
  { number: "5.16", category: "axborot-ishora", shape: "square-blue",
    nameLotin: "Turar joy hududi", nameRus: "Жилая зона",
    descLotin: "Turar joy hududi boshlanganini bildiradi, tezlik 20 km/soatdan oshmasligi kerak.",
    descRus: "Начало жилой зоны — территории, на которой действуют особые требования ПДД." },
  { number: "5.19.1", category: "axborot-ishora", shape: "rect-white",
    nameLotin: "Aholi punkti nomi", nameRus: "Начало населённого пункта",
    descLotin: "Aholi punkti chegarasi boshlanganini bildiradi.",
    descRus: "Обозначает начало населённого пункта." },
  { number: "5.31", category: "axborot-ishora", shape: "square-blue",
    nameLotin: "Tupik", nameRus: "Тупик",
    descLotin: "Yo'l tupik bilan tugashini bildiradi.",
    descRus: "Дорога с тупиком." },
  { number: "5.33", category: "axborot-ishora", shape: "square-blue", svgKey: "pedestrian-zone",
    nameLotin: "Piyodalar zonasi", nameRus: "Пешеходная зона",
    descLotin: "Faqat piyodalar harakatlanishi mumkin bo'lgan hudud boshlanganini bildiradi.",
    descRus: "Территория, по которой разрешено движение только пешеходов." },

  // --- Servis ---
  { number: "7.1", category: "servis", shape: "square-green", svgKey: "medical",
    nameLotin: "Tibbiyot punkti", nameRus: "Пункт медицинской помощи",
    descLotin: "Yaqin atrofda tibbiyot punkti borligini bildiradi.",
    descRus: "Указывает на наличие поблизости пункта медицинской помощи." },
  { number: "7.3", category: "servis", shape: "square-green", svgKey: "fuel",
    nameLotin: "Yoqilg'i quyish shoxobchasi", nameRus: "АЗС",
    descLotin: "Yaqin atrofda yoqilg'i quyish shoxobchasi borligini bildiradi.",
    descRus: "Указывает на наличие поблизости автозаправочной станции." },
  { number: "7.4", category: "servis", shape: "square-green",
    nameLotin: "Avtomobillarni yuvish", nameRus: "Мойка автомобилей",
    descLotin: "Yaqin atrofda avtomobil yuvish xizmati borligini bildiradi.",
    descRus: "Указывает на наличие поблизости мойки автомобилей." },
  { number: "7.5", category: "servis", shape: "square-green", svgKey: "phone",
    nameLotin: "Telefon", nameRus: "Телефон",
    descLotin: "Yaqin atrofda aloqa punkti borligini bildiradi.",
    descRus: "Указывает на наличие поблизости пункта связи." },
  { number: "7.6", category: "servis", shape: "square-green", svgKey: "food",
    nameLotin: "Ovqatlanish joyi", nameRus: "Пункт питания",
    descLotin: "Yaqin atrofda ovqatlanish joyi (kafe, restoran) borligini bildiradi.",
    descRus: "Указывает на наличие поблизости пункта питания." },
  { number: "7.8", category: "servis", shape: "square-green",
    nameLotin: "Mehmonxona yoki motel", nameRus: "Гостиница или мотель",
    descLotin: "Yaqin atrofda mehmonxona yoki motel borligini bildiradi.",
    descRus: "Указывает на наличие поблизости гостиницы или мотеля." },
  { number: "7.11", category: "servis", shape: "square-green",
    nameLotin: "Politsiya posti", nameRus: "Пост дорожно-патрульной службы",
    descLotin: "Yaqin atrofda yo'l-patrul xizmati posti borligini bildiradi.",
    descRus: "Указывает на наличие поблизости поста дорожно-патрульной службы." },
  { number: "7.16", category: "servis", shape: "square-green", svgKey: "parking",
    nameLotin: "To'xtash joyi", nameRus: "Место стоянки",
    descLotin: "Transport vositalarini to'xtab turish uchun maydoncha borligini bildiradi.",
    descRus: "Указывает на наличие площадки для стоянки транспортных средств." },

  // --- Qo'shimcha axborot (plates) ---
  { number: "8.1.1", category: "qoshimcha-axborot", shape: "rect-white",
    nameLotin: "Masofagacha", nameRus: "Расстояние до объекта",
    descLotin: "Asosiy belgi ko'rsatgan joygacha bo'lgan masofani bildiradi.",
    descRus: "Указывает расстояние от знака до места, откуда начинается опасный участок." },
  { number: "8.2.1", category: "qoshimcha-axborot", shape: "rect-white",
    nameLotin: "Ta'sir zonasi", nameRus: "Зона действия",
    descLotin: "Asosiy belgi amal qiladigan masofani bildiradi.",
    descRus: "Указывает протяжённость зоны действия знака." },
  { number: "8.4.1", category: "qoshimcha-axborot", shape: "rect-white",
    nameLotin: "Transport vositasi turi", nameRus: "Вид транспортного средства",
    descLotin: "Asosiy belgi faqat ko'rsatilgan turdagi transportga tegishli ekanini bildiradi.",
    descRus: "Указывает вид транспортного средства, к которому относится действие знака." },
  { number: "8.6.1", category: "qoshimcha-axborot", shape: "rect-white",
    nameLotin: "To'xtash usuli", nameRus: "Способ постановки на стоянку",
    descLotin: "Transport vositasini yo'l chekkasiga qanday qo'yish kerakligini bildiradi.",
    descRus: "Указывает способ постановки транспортного средства на стоянку." },
  { number: "8.13", category: "qoshimcha-axborot", shape: "rect-white",
    nameLotin: "Yo'nalish bo'yicha harakat", nameRus: "Направление главной дороги",
    descLotin: "Bosh yo'lning kesishmadan qanday yo'nalishda o'tishini bildiradi.",
    descRus: "Указывает направление главной дороги на пересечении." },
  { number: "8.17", category: "qoshimcha-axborot", shape: "rect-white",
    nameLotin: "Nogironlar", nameRus: "Инвалиды",
    descLotin: "Asosiy belgi faqat nogironlar boshqaradigan transportga taalluqli emasligini bildiradi.",
    descRus: "Указывает, что действие знака не распространяется на транспорт инвалидов." },

  // --- Transport vositalarining taniqlik belgilari ---
  { number: "9.1", category: "transport-taniqlik", shape: "rect-white",
    nameLotin: "Yangi haydovchi", nameRus: "Начинающий водитель",
    descLotin: "Haydovchilik tajribasi 2 yildan kam bo'lgan haydovchi boshqarayotgan avtomobilga o'rnatiladi.",
    descRus: "Устанавливается на ТС, которым управляет водитель со стажем менее 2 лет." },
  { number: "9.2", category: "transport-taniqlik", shape: "circle-white",
    nameLotin: "Nogironlar", nameRus: "Инвалид",
    descLotin: "Nogiron haydovchi boshqaradigan yoki nogironni tashiydigan avtomobilga o'rnatiladi.",
    descRus: "Устанавливается на ТС, управляемом инвалидом или перевозящем инвалида." },
  { number: "9.3", category: "transport-taniqlik", shape: "square-green",
    nameLotin: "Bolalar tashish", nameRus: "Перевозка детей",
    descLotin: "Bolalar guruhini tashiydigan avtomobilga o'rnatiladi.",
    descRus: "Устанавливается на ТС, перевозящем организованную группу детей." },
  { number: "9.5", category: "transport-taniqlik", shape: "rect-white",
    nameLotin: "Uzoq (katta) transport vositasi", nameRus: "Длинномерное транспортное средство",
    descLotin: "Uzunligi 12 metrdan ortiq transport vositasiga o'rnatiladi.",
    descRus: "Устанавливается на ТС длиной более 12 метров." },
  { number: "9.7", category: "transport-taniqlik", shape: "square-green",
    nameLotin: "O'quv transport vositasi", nameRus: "Учебное транспортное средство",
    descLotin: "Haydovchilikka o'rgatish uchun foydalaniladigan avtomobilga o'rnatiladi.",
    descRus: "Устанавливается на ТС, используемом для обучения вождению." }
];
